name: Validate code quality

env:
  NODE_VERSION: 22

on:
  push:
    branches:
      - '**'

jobs:
  eslint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci --no-audit --no-fund --no-progress
      - run: npm run lint
      - run: npm run prettier

  type-checking:
    name: Type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci --no-audit --no-fund --no-progress
      - run: npm run check-types

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci --no-audit --no-fund --no-progress
      - run: npm test
