name: Deploy GitHub pages

env:
  NODE_VERSION: 22
  GH_PAGES_DIR: gh-pages-dist

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install build dependencies
        run: npm ci --no-audit --no-fund --no-progress --prefix build
      - name: Install dependencies
        run: npm ci --no-audit --no-fund --no-progress
      - name: Build
        run: npm run build -- -- --env out=$GH_PAGES_DIR
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.GH_PAGES_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      actions: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
